/* 
 * DO NOT EDIT THIS FILE!
 *
 * This file was generated by the DecoratedD precompiler.
 * Any changes you make to this file will be modified the
 * next time you run DecoratedD.  If you would like to make
 * changes to this file, modify either the source file that
 * was used to generate this file, or the Decorator library
 * that was called by DecoratedD to generate this output.
 *
 */

#line 1 "test/senderoxc/test1.sdx"
module test1;#line 15 "test/senderoxc/mysql/test1.d"



import sendero.routing.Router, sendero.http.Request, sendero.routing.IRoute, sendero.view.View;
import sendero_base.Core, sendero.db.Bind, sendero.vm.Bind, sendero.validation.Validations;
import sendero.db.DBProvider;
import sendero.http.Request, sendero.routing.Convert;
import sendero.core.Memory;
import sendero.util.collection.StaticBitArray, sendero.util.Singleton;

#line 1 "test/senderoxc/test1.sdx"


import test2;
import IUser;

import dummy;

/+@controller+/ class MainCtlr#line 34 "test/senderoxc/mysql/test1.d"

: IIController
#line 8 "test/senderoxc/test1.sdx"

{
	/+@GET+/
	static Res index()
	{
	
	}

	/+@POST+/
	static Res login(char[] username, char[] password)
	{

	}
	
	/+@GET+/
	static Res logout()
	{
	
	}
	
	/+@POST+/
	static Res signup(char[] firstname, char[] lastname, char[] email,
						char[] pswd, char[] pswdConfirm)
	{
		
	}
	
	/+@POST+/
	static Res resetPswd(char[] email)
	{
	
	}
	
	static IIController getInstance(Req req)
	{
		
	}
#line 75 "test/senderoxc/mysql/test1.d"

static const TypeSafeRouter!(Req) r;
static const TypeSafeInstanceRouter!(Req) ir;
static this()
{
	r = TypeSafeRouter!(Req)();
	ir = TypeSafeInstanceRouter!(Req)();
	r.map!(Res function())(GET,"", &MainCtlr.index, []);
	r.map!(Res function(char[],char[]))(POST,"login", &MainCtlr.login, ["username", "password"]);
	r.map!(Res function())(GET,"logout", &MainCtlr.logout, []);
	r.map!(Res function(char[],char[],char[],char[],char[]))(POST,"signup", &MainCtlr.signup, ["firstname", "lastname", "email", "pswd", "pswdConfirm"]);
	r.map!(Res function(char[]))(POST,"resetPswd", &MainCtlr.resetPswd, ["email"]);
}

static void route(Req req)
{ return r.route(req); }
void iroute(Req req)
{ return ir.route(req, cast(void*)this); }

#line 45 "test/senderoxc/test1.sdx"
}

/+@controller+/ class UserCtlr#line 98 "test/senderoxc/mysql/test1.d"

: IIController
#line 47 "test/senderoxc/test1.sdx"

{
	/+@POST+/
	Res changePswd(char[] curPswd, char[] newPswd, char[] newPswdConfirm)
	{
	
	}
#line 109 "test/senderoxc/mysql/test1.d"

static const TypeSafeRouter!(Req) r;
static const TypeSafeInstanceRouter!(Req) ir;
static this()
{
	r = TypeSafeRouter!(Req)();
	ir = TypeSafeInstanceRouter!(Req)();
	ir.map!(Res function(char[],char[],char[]))(POST,"changePswd", &UserCtlr.changePswd, ["curPswd", "newPswd", "newPswdConfirm"]);
}

static void route(Req req)
{ return r.route(req); }
void iroute(Req req)
{ return ir.route(req, cast(void*)this); }

#line 54 "test/senderoxc/test1.sdx"
}

/+@controller+/ class GroupCtlr#line 128 "test/senderoxc/mysql/test1.d"

: IIController
#line 56 "test/senderoxc/test1.sdx"

{
	/+@GET+/
	static Res create()
	{
	
	}
	
	/+@POST+/
	static Res create()
	{
	
	}
#line 145 "test/senderoxc/mysql/test1.d"

static const TypeSafeRouter!(Req) r;
static const TypeSafeInstanceRouter!(Req) ir;
static this()
{
	r = TypeSafeRouter!(Req)();
	ir = TypeSafeInstanceRouter!(Req)();
	r.map!(Res function())(GET,"create", &GroupCtlr.create, []);
	r.map!(Res function())(POST,"create", &GroupCtlr.create, []);
}

static void route(Req req)
{ return r.route(req); }
void iroute(Req req)
{ return ir.route(req, cast(void*)this); }

#line 69 "test/senderoxc/test1.sdx"
}


/+@data+/ class User#line 166 "test/senderoxc/mysql/test1.d"

: IUser
#line 72 "test/senderoxc/test1.sdx"

{
	/+@primaryKey+/ /+@autoIncrement+/ /+@UInt("id")+/;
	/+@required+/ /+@String("email")+/;
	/+@minLength(8)+/ /+@maxLength(40)+/ /+@String("username")+/; 
	/+@String("firstname")+/;
	/+@String("lastname")+/;
	/+@Time("last_login")+/;
#line 178 "test/senderoxc/mysql/test1.d"

static this()
{
	Construct!(IUser).register(&create);
}
static IUser create()
{
	return new User;
}
private static MinLengthValidation username_MinLengthValidation;
private static MaxLengthValidation username_MaxLengthValidation;

bool validate()
{
	bool succeed = true;

	void fail(char[] field, Error err)	{
		succeed = false;
		__errors__.add(field, err);
	}

	if(!ExistenceValidation!(char[]).validate(email_)) fail("email_", ExistenceValidation!(char[]).error);
	if(!username_MinLengthValidation.validate(username_)) fail("username_", username_MinLengthValidation.error);
	if(!username_MaxLengthValidation.validate(username_)) fail("username_", username_MaxLengthValidation.error);

	return succeed;
}


mixin SessionAllocate!();

ErrorMap errors()
{
	return __errors__;
}
void clearErrors()
{
	__errors__.reset;
}
private ErrorMap __errors__;
alias DefaultMysqlProvider db;
public void destroy()
{
	const char[] deleteSql = "DELETE FROM `User` WHERE `id` = ?";
	scope st = db.prepare(deleteSql);
	st.execute(id);
}

bool save()
{
	auto db = getDb;
	char[][6] fields;
	BindType[6] bindTypes;
	void*[6] bindPtrs;
	BindInfo bindInfo;
	uint idx = 0;
	if(__touched__[1]) {malformed format}) { fields[idx] = "email"; ++idx;}
	if(__touched__[2]) {malformed format}) { fields[idx] = "username"; ++idx;}
	if(__touched__[3]) {malformed format}) { fields[idx] = "firstname"; ++idx;}
	if(__touched__[4]) {malformed format}) { fields[idx] = "lastname"; ++idx;}
	if(__touched__[5]) {malformed format}) { fields[idx] = "last_login"; ++idx;}
	if(id_) { fields[idx] = "id"; ++idx; }
	bindInfo.types = setBindTypes(fields[0..idx], bindTypes);
	bindInfo.ptrs = setBindPtrs(field[0..idx], bindPtrs);
	if(id_) {
		auto res = db.update("User", fields[0..idx], "WHERE id = ?", bindInfo);
		if(db.affectedRows == 1) return true; else return false;
	}}
	else {
		auto res = db.insert("User", fields[0..idx], bindInfo);
		id_ = db.lastInsertID;
		if(id_) return true; else return false;
	}}
}

Var opIndex(char[] key)
{
	Var res;
	switch(key)
	{
		case "id": bind(res, id()); break;
		case "email": bind(res, email()); break;
		case "username": bind(res, username()); break;
		case "firstname": bind(res, firstname()); break;
		case "lastname": bind(res, lastname()); break;
		case "last_login": bind(res, last_login()); break;
		default: return Var();
	}
	return res;
}
int opApply (int delegate (inout char[] key, inout Var val) dg)
{
	int res; char[] key; Var val;
	key = "id"; bind(val, id()); if((res = dg(key, val)) != 0) return res;
	key = "email"; bind(val, email()); if((res = dg(key, val)) != 0) return res;
	key = "username"; bind(val, username()); if((res = dg(key, val)) != 0) return res;
	key = "firstname"; bind(val, firstname()); if((res = dg(key, val)) != 0) return res;
	key = "lastname"; bind(val, lastname()); if((res = dg(key, val)) != 0) return res;
	key = "last_login"; bind(val, last_login()); if((res = dg(key, val)) != 0) return res;
	return res;
}
void opIndexAssign(Var val, char[] key) {}
Var opCall(Var[] params, IExecContext ctxt) { return Var(); }
void toString(IExecContext ctxt, void delegate(char[]) utf8Writer, char[] flags = null) {}


protected StaticBitArray!(1,6) __touched__;


void httpSet(IObject obj, Request req)
{
	foreach(key, val; obj)
	{
		switch(key)
		{
			case "email": email_ = convertParam!(char[], Req)(val, req); break;
			case "username": username_ = convertParam!(char[], Req)(val, req); break;
			case "firstname": firstname_ = convertParam!(char[], Req)(val, req); break;
			case "lastname": lastname_ = convertParam!(char[], Req)(val, req); break;
			case "last_login": last_login_ = convertParam!(Time, Req)(val, req); break;
			default: break;
		}
	}
}

BindType[] setBindTypes(char[][] fieldNames, BindType[] dst)
{
	assert(dst.length >= 6, "Must provide an array of at least length 6 to bind items to class User");
	size_t idx = 0;
	foreach(name;fieldNames) {
		switch(name) {
		case "id": dst[i] = BindType.UInt; break;
		case "email": dst[i] = BindType.String; break;
		case "username": dst[i] = BindType.String; break;
		case "firstname": dst[i] = BindType.String; break;
		case "lastname": dst[i] = BindType.String; break;
		case "last_login": dst[i] = BindType.Time; break;
		}
		++idx;
	}
	return dst[0..idx];
}
void*[] setBindPtrs(char[][] fieldNames, void*[] dst)
{
	assert(dst.length >= 6, "Must provide an array of at least length 6 to bind items to class User");
	size_t idx = 0;
	foreach(name;fieldNames) {
		switch(name) {
		case "id": dst[i] = &this.id_; break;
		case "email": dst[i] = &this.email_; break;
		case "username": dst[i] = &this.username_; break;
		case "firstname": dst[i] = &this.firstname_; break;
		case "lastname": dst[i] = &this.lastname_; break;
		case "last_login": dst[i] = &this.last_login_; break;
		}
		++idx;
	}
	return dst[0..idx];
}
ptrdiff_t[] setBindPtrs(char[][] fieldNames, ptrdiff_t[] dst)
{
	assert(dst.length >= 6, "Must provide an array of at least length 6 to bind items to class User");
	size_t idx = 0;
	foreach(name;fieldNames) {
		switch(name) {
		case "id": dst[i] = &this.id_ - &this; break;
		case "email": dst[i] = &this.email_ - &this; break;
		case "username": dst[i] = &this.username_ - &this; break;
		case "firstname": dst[i] = &this.firstname_ - &this; break;
		case "lastname": dst[i] = &this.lastname_ - &this; break;
		case "last_login": dst[i] = &this.last_login_ - &this; break;
		}
		++idx;
	}
	return dst[0..idx];
}

public uint id() { return id_; }
private uint id_;

public char[] email() { return email_; }
public void email(char[] val) {__touched__[1] = true; email_ = val;}
private char[] email_;

public char[] username() { return username_; }
public void username(char[] val) {__touched__[2] = true; username_ = val;}
private char[] username_;

public char[] firstname() { return firstname_; }
public void firstname(char[] val) {__touched__[3] = true; firstname_ = val;}
private char[] firstname_;

public char[] lastname() { return lastname_; }
public void lastname(char[] val) {__touched__[4] = true; lastname_ = val;}
private char[] lastname_;

public Time last_login() { return last_login_; }
public void last_login(Time val) {__touched__[5] = true; last_login_ = val;}
private Time last_login_;

#line 80 "test/senderoxc/test1.sdx"
}
