/* 
 * DO NOT EDIT THIS FILE!
 *
 * This file was generated by the DecoratedD precompiler.
 * Any changes you make to this file will be modified the
 * next time you run DecoratedD.  If you would like to make
 * changes to this file, modify either the source file that
 * was used to generate this file, or the Decorator library
 * that was called by DecoratedD to generate this output.
 *
 */

#line 1 "test/senderoxc/IUser.sdx"
module IUser;#line 15 "test/senderoxc/IUser.d"




#line 1 "test/senderoxc/IUser.sdx"


/+@dataInterface("User")+/;#line 23 "test/senderoxc/IUser.d"

interface IUser : IObject, IHttpSet
{
	void destroy();
	bool save();
	uint id();
	char[] email();
	void email(char[]);
	char[] username();
	void username(char[]);
	char[] firstname();
	void firstname(char[]);
	char[] lastname();
	void lastname(char[]);
	Time last_login();
	void last_login(Time);
}
alias Construct!(IUser).create constructUser;
